- name: Comment Webpage Screenshot
  # You may pin to the exact commit or the version.
  # uses: saadmk11/comment-webpage-screenshot@9de0dca8ecf38509006b81474522e7d4de17b03e
  uses: saadmk11/comment-webpage-screenshot@v0.5
  with:
    # Service to use for uploading the screenshots. (Options: github_branch, imgur)
    upload_to: # optional, default is github_branch
    # Capture Screenshots of Changed/Added HTML Files. (Options: yes, no)
    capture_changed_html_files: # optional, default is yes
    # Capture Screenshot of HTML Files Seperated by Comma.
    capture_html_file_paths: # optional
    # Capture Screenshot of URLs Seperated by Comma.
    capture_urls: https://ransom.insicurezzadigitale.com/chart-png-ita.php # optional
    # GITHUB_TOKEN or Personal Access Token (PAT)
    github_token: # optional, default is ${{ github.token }}
