name: Publish

on: [push]

jobs:
  create-screenshot:
    runs-on: ubuntu-latest
    name: 'Schedule Screenshot Creation'
    steps:
      - uses: websiteshot/github-action@main
        env:
          PROJECT_ID: ${{ secrets.PROJECT_ID }}
          API_KEY: ${{ secrets.API_KEY }}
          URLS: '[{"url": "https://websiteshot.app", "name": "Websiteshot"}]'
          SCHEDULE_UNIT: 'm'
          SCHEDULE_VALUE: '5'
